title: AI Trace Viewer Documentation
description: View structured logs as execution trees
url: "https://pexmor.github.io"
baseurl: "/mytrace"
repository: "PexMor/mytrace"

# Minimal Mistakes theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Author
author:
  name: "AI Trace Viewer Team"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/PexMor/mytrace"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/PexMor/mytrace"

# Reading Files
include:
  - _pages
  - app

# Exclude files/directories from Jekyll processing
exclude:
  - vendor/
  - .bundle/
  - Gemfile
  - Gemfile.lock
  - archive/        # Archived documentation
  - "*.sh"          # Shell scripts
  - install_web.sh
  - run_web.sh

# Plugins (required for minimal-mistakes)
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

# Default front matter for pages
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # docs
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "docs"

# Suppress Sass deprecation warnings (from theme, not our code)
sass:
  quiet_deps: true
  style: compressed
  silence_deprecations:
    - import
    - color-functions
    - global-builtin
    - slash-div
