source "https://rubygems.org"

gem "jekyll"
gem "minimal-mistakes-jekyll"

# Required plugin for minimal-mistakes
gem "jekyll-include-cache"

# Recommended plugins
gem "jekyll-feed"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"

# Utilities
gem "logger"          # Silence Ruby 3.5 warning